name: chocolatine
run-name: ${{ github.actor }} is the project chocolatine
on:
   push:
     branches:
       - '**'
       - ! 'ga-ignore-**'
   pull request:
     branches:
       - '**'
       - ! 'ga-ignore-**'

env:
  MIRROR_URL: https://github.com/EpitechPGEPromo2029/B-DOP-200-COT-2-1-chocolatine-amyrath.chakran.git
  EXECUTABLES: directory1/executableA,directory2/executableB

jobs:
  check_coding_style:
  Explore-GitHub-Actions:
  runs-on: ubuntu-latest
  container: ghcr.io/epitech/coding-style-checker:latest
  steps:
    - name: the checkout base
    - uses: actions/checkout@v4
    - name: chech coding style
    - run: |
        check.sh $(pwd) $(pwd)
        if [coding-style-reports.log]; then
          cat coding-style-reports.log
          exit 1
        fi